### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jpark052** [CobeyH/MothLight2D#104]
This is our roadmap to finish this project.

### September
- [x] Background blur fix
- [x] New menus testing
- [ ] Template for new levels
- [ ] Improve visual of the frog
- [ ] Cleaning the light limit
- [ ] Auto play sequence fix
- [ ] Cohesive design
- [ ] Build up to 5 levels
- [ ] Test above 5 levels

### October
- [ ] Build up to 30 levels
- [ ] Test all levels

### November
- [ ] Deploy to Steam 🎉
- [ ] Bug fix after deployment

### December
Hopefully everything is done by December!

### Important Dates
Jae leaving on Dec 15th-ish
Cobey leaving on Dec 28th
